### ISSUE TITLE
Error Message on Customizer Page

### ISSUE THREAD

**Issue by RcLLC** [html2wp/simple-live-editor#6]
Hello,

Im new here, the site im working on is 5050fest.com. I use an Adobe Muse file them converted it with htmltowordpress.io.

When I go to try to live edit I received the following error message: 

Fatal error: Call to undefined method stdClass::markup() in /home/content/46/9393346/html/5050/wp-content/plugins/simple-live-editor-master/vendor/html2wp/phpquery/phpQuery/phpQuery/DOMDocumentWrapper.php on line 557

How can I fix?

**Comment by harzzn** [comment]
Hi, thanks for reporting this! Could you let me know if this is working in the theme-preview environment on our website or is the error happening only on your server? If so please try updating your PHP version to 5.4 if applicable and let me know if you are still experiencing this error.

Best, Harri

**Comment by harzzn** [comment]
Most likely wrong PHP version
